### PR TITLE
Validate database prefix against DBNAME_REGEX for system dbs

### LINKED ISSUE #1644: Illegal DB creation permitted
Reported/asked about here: https://stackoverflow.com/q/52636973/13860

## Expected Behavior

Creating a database called `!abcdef/_users` should fail, due to invalid DB name.

## Current Behavior

DB creation succeeds:

    curl -v -X PUT http://admin:abc123@localhost:6004/\!abcdef%2F_users
    *   Trying ::1...
    * TCP_NODELAY set
    * Connected to localhost (::1) port 6004 (#0)
    * Server auth using Basic with user 'admin'
    > PUT /!abcdef%2F_users HTTP/1.1
    > Host: localhost:6004
    > Authorization: Basic YWRtaW46YWJjMTIz
    > User-Agent: curl/7.52.1
    > Accept: */*
    > 
    < HTTP/1.1 201 Created
    < Cache-Control: must-revalidate
    < Content-Length: 12
    < Content-Type: application/json
    < Date: Sun, 07 Oct 2018 11:21:46 GMT
    < Location: http://localhost:6004/%21abcdef%2F_users
    < Server: CouchDB/2.2.0 (Erlang OTP/19)
    < X-Couch-Request-ID: 8d5c83b3a4
    < X-CouchDB-Body-Time: 0
    < 
    {"ok":true}
    * Curl_http_done: called premature == 0
    * Connection #0 to host localhost left intact

## Possible Solution

Seems likely that the "special case" for `_users` is just too permissive, such as a regex not bound to the beginning of the string, or a similar error.

## Steps to Reproduce (for bugs)

See curl command above.

## Your Environment

* Version used: CouchDB 2.2.0 via official Docker image
* Browser Name and version: curl 7.52.1
* Operating System and version (desktop or mobile): Debian 9.5

### PR DESCRIPTION
**Pull request by iilyak**
## Overview

Previously we only checked that the suffix of the database is
matching one of the predefined system databases. We really should
check the prefix against DBNAME_REGEXP to prevent creation of
illegally named databases.

## Testing recommendations

```
make eunit apps=couch tests=validate_dbname_fail_test_,validate_dbname_success_test_,is_systemdb_test_
```

## Related Issues or Pull Requests

This fixes #1644 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by lazedo** [comment]
hello,

i just want to make sure that this doesn't break our current usage.
we create DBs with names like this `account%2F85%2Fea%2F6075c6c1e266f8512e2233541bdb-201807`

**Comment by iilyak** [comment]
@lazedo 

It would still work:
```
(node1@127.0.0.1)3> couch_db:validate_dbname("account/85/ea/6075c6c1e266f8512e2233541bdb-201807").
ok
```

File: src/couch/src/couch_db.erl [hunk 1]
```diff
@@ -1738,8 +1738,16 @@ validate_dbname_int(DbName, Normalized) when is_binary(DbName) ->
...
-
+    Normalized = normalize_dbname(DbName),
+    Suffix = filename:basename(Normalized),
+    case {filename:dirname(Normalized), lists:member(Suffix, ?SYSTEM_DATABASES)} of
+        {<<".">>, Result} -> Result;
+        {Prefix, false} -> false;
+        {Prefix, true} ->
+            re:run(Prefix, ?DBNAME_REGEX, [{capture,none}, dollar_endonly])
+            ==
+            match
```
Comment (jaydoane) [inline src/couch/src/couch_db.erl]: Not sure why `== match` are not on the same line, but I guess it's not a big deal.

**Comment by jaydoane** [comment]
```
=======================================================
  All 144 tests passed.
```

File: src/couch/src/couch_db.erl (hunk 1 above)
Comment (iilyak) [reply src/couch/src/couch_db.erl]: I wish we (CouchDB community) have a syntax guidelines. I agree, this formatting is a bit haskellish (or ocamellish). However it provides a good structure visually which helps when reading the code. Although it could be just me because I used to this formatting. Let me know if you want me to change it and which one you would prefer.

1. operand (new line) operator (new line) operand
```
re:run(Prefix, ?DBNAME_REGEX, [{capture,none}, dollar_endonly])
==
match
```
2. operand (new line) (extra indent) operator operand
```
re:run(Prefix, ?DBNAME_REGEX, [{capture,none}, dollar_endonly])
    == match
```
3. operand (new line) operator operand
```
re:run(Prefix, ?DBNAME_REGEX, [{capture,none}, dollar_endonly])
== match
```
4. extract this into a function `match_regexp/1` and use it in other places as well.

Comment (eiri) [reply src/couch/src/couch_db.erl]: personally I'd split it i two lines
```
ReOpts =  [{capture,none}, dollar_endonly]
re:run(Prefix, ?DBNAME_REGEX, ReOpts) == match
```
as it is right now looks more markupish than haskellish to me.

File: src/couch/src/couch_db.erl [hunk 2]
```diff
@@ -1738,8 +1738,15 @@ validate_dbname_int(DbName, Normalized) when is_binary(DbName) ->
 is_systemdb(DbName) when is_list(DbName) ->
     is_systemdb(?l2b(DbName));
 is_systemdb(DbName) when is_binary(DbName) ->
-    lists:member(dbname_suffix(DbName), ?SYSTEM_DATABASES).
-
+    Normalized = normalize_dbname(DbName),
+    Suffix = filename:basename(Normalized),
+    case {filename:dirname(Normalized), lists:member(Suffix, ?SYSTEM_DATABASES)} of
+        {<<".">>, Result} -> Result;
+        {Prefix, false} -> false;
```
Comment (jiangphcn) [inline src/couch/src/couch_db.erl]: Just happen to find warning `.../db/src/couchdb/src/couch/src/couch_db.erl:1748: Warning: variable 'Prefix' is unused`
