### PR TITLE
Fix #1988 - Validate attachment names on POST /db/doc

### LINKED ISSUE #1988: Attachments operations PUT /db/doc & POST /db perform inconsistent attachment name validation
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

PUT & POST operations for creating documents in a database enforce different validation rules over the attachment names of the new document.

When a document is created with a PUT operation "_foo.txt" is not accepted as a valid attachment name. If the document is created by a POST operation the "_foo.txt" attachment name is accepted.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

## Steps to Reproduce

- Create a new document with an attachment with the name "_foo.txt" using PUT
```
 curl -H 'Content-Type: application/json' -X PUT \ 
-d '{"_id": "bin_doc2",  "_attachments": { "_foo.txt": { "content_type": "text/plain", "data":"VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ="}}}'  \ 
http://localhost:15984/test/bin_doc2 
```
- An error is returned stating that _foo.txt is not allowed as attachment name as it starts by _
````
{"error":"bad_request","reason":"Attachment name '_foo.txt' starts with prohibited character '_'"}
````
- Create a new document with an attachment with the name "_foo.txt" using POST
```
curl -H 'Content-Type: application/json' -X POST \ 
-d '{"_id": "bin_doc2", "_attachments": { "_foo.txt": { "content_type": "text/plain", "data":"VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ="}}}' \ 
http://localhost:15984/test
```
- Document is created which seems to be wrong
```
{"ok":true,"id":"bin_doc2","rev":"1-92cd355222a3c08e725e08ba14259e60"}
```
- Attachment with _ can be retrieved (no attachment name restriction is enforced)
```
> curl http://localhost:15984/test/bin_doc2/_foo.txt
> This is a base64 encoded text
```
- Attachment can not be deleted (In this case attachent name is validated)
```
> curl -X DELETE http://localhost:15984/test/bin_doc2/_foo.txt?rev=1-92cd355222a3c08e725e08ba14259e60
> {"error":"bad_request","reason":"Attachment name '_foo.txt' starts with prohibited character '_'"}
```
- Attachment can not be updated (In this case attachent name is validated)
```
< curl -H 'Content-Type: text/plain' -X PUT -d 'VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ=' http://localhost:15984/test/bin_doc2/_foo.txt?rev=1-92cd355222a3c08e725e08ba14259e60
> {"error":"bad_request","reason":"Attachment name '_foo.txt' starts with prohibited character '_'"}
```

POST document, and GET attachment operations seem to be not enforcing attachment filename validation rules which is an inconsistent behaviour.

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

## Expected Behaviour

PUT & POST should enforce the same validation rules over the document

GET attachment should enforce attachment filename valiation rules

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

```
{
  "couchdb": "Welcome",
  "version": "2.3.0-8efe9b290",
  "git_sha": "8efe9b290",
  "uuid": "fake_uuid_for_dev",
  "features": [
    "partitioned",
    "pluggable-storage-engines",
    "scheduler"
  ],
  "vendor": {
    "name": "The Apache Software Foundation"
  }
}
```
[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB Version used: Built from master  (2.3.0-8efe9b290)
* Browser name and version:
* Operating System and version: MacOS 10.14.3

## Additional context

[TIP]:  # ( Add any other context about the prbolem here. )

### PR DESCRIPTION
**Pull request by jjrodrig**
## Overview
 This PR solves the problem described at the issue #1988 

PUT & POST operations for creating documents in a database enforce different validation rules over the attachment names of the new document.

When a document is created with a PUT operation "_foo.txt" is not accepted as a valid attachment name. If the document is created by a POST operation the "_foo.txt" attachment name is accepted.

This is an inconsistent behavoiur in the API as not accepted attachment names can be created. 

## Testing recommendations

```
make elixir tests=test/attachment_names_test.exs
```

## Related Issues or Pull Requests
 This PR fixes #1988 

## Checklist

- [X] Code is written and works correctly;
- [X] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

**Comment by wohali** [comment]
Hi @jjrodrig , any desire to get this updated and merged into the `3.x` and `3.0.x` branches as well?

**Comment by jjrodrig** [comment]
Sure @wohali 

As soon this PR is accepted, I'll open PRs to merge into the 3.x and 3.0.x branches

File: src/chttpd/src/chttpd_db.erl [hunk 1]
```diff
@@ -1432,6 +1433,7 @@ couch_doc_open(Db, DocId, Rev, Options0) ->
 db_attachment_req(#httpd{method='GET',mochi_req=MochiReq}=Req, Db, DocId, FileNameParts) ->
     FileName = list_to_binary(mochiweb_util:join(lists:map(fun binary_to_list/1,
         FileNameParts),"/")),
+    validate_attachment_name(FileName),
```
Comment (rnewson) [inline src/chttpd/src/chttpd_db.erl:1436]: why validate on GET?

File: src/chttpd/src/chttpd_db.erl [hunk 2]
```diff
@@ -1736,7 +1738,7 @@ parse_partitioned_opt(Req) ->
 
 validate_partitioned_db_enabled(Req) ->
     case couch_flags:is_enabled(partitioned, Req) of
-        true -> 
+        true ->
```
Comment (rnewson) [inline src/chttpd/src/chttpd_db.erl:1741]: remove whitespace only change

File: src/chttpd/src/chttpd_db.erl (hunk 1 above)
Comment (jjrodrig) [reply src/chttpd/src/chttpd_db.erl:1436]: Just to be consistent in the API response and return 400 when the attachment name is not valid. 
We can remove the validation and just return 404

Comment (jjrodrig) [reply src/chttpd/src/chttpd_db.erl:1436]: @rnewson Do you think that we should return 404 and not 400 when a not allowed attachment name is requested?

File: src/chttpd/src/chttpd_db.erl (hunk 2 above)
Comment (jjrodrig) [reply src/chttpd/src/chttpd_db.erl]: Done

**Comment by wohali** [comment]
@jjrodrig @rnewson any plans to get this in? I am preparing to mass-close old PRs that never got merged.

**Comment by jjrodrig** [comment]
@wohali I'll update this and move it to main

**Review by rnewson — APPROVED** [review]
lgtm
