### PR TITLE
Fix/single node status 3.0.x

### LINKED ISSUE #2557: Unexpected cluster state for single node config
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

With CouchDB 3.x (#2296) we have the option to setup a node as "single node" via config setting. I expected this to have the same effect like using the Fauxton cluster setup UI from CouchDB 2.x.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

Using the new config setting we get the following cluster state at `/_cluster_setup`:

```{"state":"cluster_finished"}```

When using the Fauxton based single node setup, the `/_cluster_setup` endpoint returns:

```{"state":"single_node_enabled"}```

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

```
git clone https://github.com/apache/couchdb-docker
cd couchdb-docker/
echo -e "\n[couchdb]\nsingle_node = true\n" >> dev/local.ini 
docker build -t couchdb:3 dev
docker run --rm -it --env COUCHDB_USER=admin --env COUCHDB_PASSWORD=password -p 5984:5984 couchdb:3
curl --user admin:password -X GET "http://localhost:5984/_cluster_setup" 
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

`GET /_cluster_setup` should return `single_node_enabled` when the new `couchdb.single_node=true` setting has been used.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

* CouchDB version used: `CouchDB/3.0.0-8748310 (Erlang OTP/21)`
* Operating system and version: Docker image based on [docker-couchdb](https://github.com/apache/couchdb-docker) (`docker build -t couchdb:3 dev`)

### PR DESCRIPTION
**Pull request by janl**
Really fix #2557 

so sorry for getting the merge base wrong four times in a row

### CODE REVIEW

File: src/setup/src/setup_httpd.erl [hunk 1]
```diff
@@ -31,24 +31,30 @@ handle_setup_req(#httpd{method='GET'}=Req) ->
...
+        true ->
+            chttpd:send_json(Req, 200, {[{state, single_node_enabled}]});
         _ ->
-            case setup:is_cluster_enabled() of
-                false ->
-                    chttpd:send_json(Req, 200, {[{state, cluster_disabled}]});
-                true ->
-                    case setup:has_cluster_system_dbs(Dbs) of
+            case erlang:list_to_integer(config:get("cluster", "n", undefined)) of
+                1 ->
```
Comment (nickva) [inline src/setup/src/setup_httpd.erl]: if it `undefined` it will blow up here? I think we'd want `config:get("cluster", "n", "1")` ?
