### PR TITLE
Fixes for _local doc update and _bulk_docs operations with new_edits false

### LINKED ISSUE #1628: Possible to write `_local` docs into the revisioned doc tree
## Expected Behavior

Expect `_local` prefixed docs not to end up in the normal versioned doc tree.

## Current Behavior

If using `_bulk_docs` and `"new_edits":false` it is possible to write a `_local` prefixed doc into the normal doc tree. Once it is there it is not possible to read or delete the document via normal means. The document is included in `_changes` `_all_docs` and replications. It also plays havoc with the dashboard where it is visible in the document list, but the document cannot be deleted nor can the content be retrieved.

## Possible Solution

I wasn't able to reproduce when using the default `"new_edits":true`, so perhaps whatever checks are made for `_local` docs there could be extended to the `"new_edits": false` case.

## Steps to Reproduce (for bugs)

1. Create DB
    `curl -XPUT http://localhost:5984/test` -->
    `{"ok":true}`
1. Write `_local/test` doc with a `_rev`
    `curl -XPOST -HContent-Type:application/json http://localhost:5984/test/_bulk_docs -d '{"new_edits":false,"docs":[{"_id":"_local/test","_rev":"1-abcdef","hello":"world"}]}'` -->
    `[]`
1. Try to `GET` the `_local/test` doc
    `curl http://localhost:5984/test/_local/test` -->
   `{"error":"not_found","reason":"missing"}`
1. Try to `GET` the `_local/test` doc via `_all_docs`
    `curl 'http://localhost:5984/test/_all_docs?key="_local/test"&include_docs=true'` -->
    `{"total_rows":1,"offset":0,"rows":[
{"id":"_local/test","key":"_local/test","value":{"rev":"1-abcdef"},"doc":{"_id":"_local/test","_rev":"1-abcdef","hello":"world"}}
]}`
1. Try to delete the `_local/test` doc
    `curl -XDELETE http://localhost:5984/test/_local/test` -->
    `{"error":"not_found","reason":"missing"}`
1. Try to delete via `_bulk_docs` and `_deleted` flag
    `curl -XPOST -HContent-Type:application/json http://localhost:5984/test/_bulk_docs -d '{"docs":[{"_id":"_local/test","_rev":"1-abcdef","_deleted":true}]}` -->
    `[{"id":"_local/test","error":"unknown_error","reason":"undefined"}]`
1. Try to delete via `_bulk_docs` and `_deleted` flag with `"new_edits":false`
    `curl -XPOST -HContent-Type:application/json http://localhost:5984/test/_bulk_docs -d '{"new_edits":false, "docs":[{"_id":"_local/test","_rev":"1-abcdef","_deleted":true}]}` -->
    `[]`

## Context

A user wrote a document with a [`_local` prefixed `_id` and a `_rev` into a local datastore in our sync-android library](https://github.com/cloudant/sync-android/issues/589). Once that was in the local store it made it into our replication path and was written to the server via `_bulk_docs` with `"new_edits":false` (as all docs that need replicating do).

Clearly we could make some improvements to sync-android in terms of documentation or preventing the insertion of a doc with `_local` prefix and a rev into its local database, but I think there is a genuine issue that needs resolving in CouchDB as well in that the server side `_bulk_docs` API has similar problems in allowing a `_local` prefixed doc to be written into the wrong part of a database, especially because it creates a document that is not removable via the normal HTTP APIs.

## Your Environment

* Version used: 2.2.0 (I've also reproduced on 1.7.2)
* Browser Name and version: Firefox 60.2.1 (for dashboard)
* Operating System and version (desktop or mobile): Docker `couchdb` image (but reproducible in other envs)
* Link to your project: https://github.com/cloudant/sync-android

### PR DESCRIPTION
**Pull request by eiri**
## Overview

This PR is mostly a refactoring and addresses the following issues:

- Attempt to create a local document with an invalid revision throwing `badarg` exception.
- The documents with `_local` prefix written into a wrong btree on a bulk operation with `new_edits` set to `false`.
- It is possible to create a document with an empty id on a bulk operation with `new_edits` set to  `false`

## Testing recommendations

New tests are expected to pass.

For manual testing here is an expected change of behaviour:

Readable error on an invalid rev for a local doc creation
``` 
curl -X PUT http://127.0.0.1:15984/koi/_local/alice?rev=0-abcdf -d '{"name":"Alice"}'
{"error":"error","reason":"Invalid rev format"}
```

Correct creation of a local doc on a bulk update
```
$ curl -X POST http://127.0.0.1:15984/koi/_bulk_docs -d '{"new_edits":false, "docs": [{"_id":"_local/alice", "_rev":"0-1", "name":"Alice"}]}'
[]
$ curl http://127.0.0.1:15984/koi/_local/alice
{"_id":"_local/alice","_rev":"0-2","name":"Alice"}
```

Generation of a missing id on a bulk update
```
$ curl -X POST http://127.0.0.1:15984/koi/_bulk_docs -d '{"new_edits":false, "docs": [{"_rev":"1-abcdefgh", "name":"Alice"}]}'
[]
$ curl http://127.0.0.1:15984/koi/_all_docs -G -d include_docs=true
{"total_rows":1,"offset":0,"rows":[
{"id":"ce4c2d25c9d580c1c5e06a05bb000443","key":"ce4c2d25c9d580c1c5e06a05bb000443","value":{"rev":"1-abcdefgh"},"doc":{"_id":"ce4c2d25c9d580c1c5e06a05bb000443","_rev":"1-abcdefgh","name":"Alice"}}
]}
```

## Related Issues or Pull Requests

This closes #1628 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

File: src/couch/src/couch_db_updater.erl [hunk 1]
```diff
@@ -627,28 +627,35 @@ update_docs_int(Db, DocsList, LocalDocs, MergeConflicts, FullCommit) ->
...
-            true  ->
-                0
-        end,
-        send_result(Client, NewDoc, {ok, {0, integer_to_binary(NewRev)}}),
-        NewDoc#doc{
-            revs = {0, [NewRev]}
-        }
-    end, Docs).
+    lists:foldl(fun({Client, NewDoc}, Acc) ->
+        try
```
Comment (iilyak) [inline src/couch/src/couch_db_updater.erl]: WARNING: Most likely very subjective proposal. How about creating a function `increment_revision(#doc{}) -> #doc{} | undefined` and put try/catch there. Then we can rewrite foldl as follows:
```
lists:foldl(fun({Client, NewDoc}, Acc) ->
   case increment_revision(NewDoc) of
      #doc{revs = {0, [NewRev]}} = Doc ->
          send_result(Client, Doc, {ok, {0, integer_to_binary(NewRev)}}),
          [Doc | Acc];
      _ -> 
          send_result(Client, NewDoc, {error, <<"Invalid rev format">>}),
          Acc
   end
end, [], Docs).
```

File: src/couch/src/couch_db.erl [hunk 2]
```diff
@@ -1314,13 +1281,42 @@ prepare_doc_summaries(Db, BucketList) ->
...
+    BucketList = group_alike_docs(Docs2),
+
+    DocBuckets = lists:map(fun(Bucket) ->
+        lists:map(fun(Doc) ->
+            DocWithBody = couch_doc:with_ejson_body(Doc),
+            couch_db_plugin:before_doc_update(Db, DocWithBody)
+        end, Bucket)
+    end, BucketList),
+
+    ValidatePred = fun
```
Comment (iilyak) [inline src/couch/src/couch_db.erl]: 💯

File: src/couch/src/couch_db_updater.erl [hunk 3]
```diff
@@ -808,3 +815,64 @@ hibernate_if_no_idle_limit() ->
...
+        {"Test local doc with invalid rev", fun t_bad_local_doc/0},
+        {"Test deleted local doc", fun t_dead_local_doc/0}
+    ]}.
+
+
+t_good_local_doc() ->
+    Doc = #doc{
+        id = <<"_local/alice">>,
+        revs = {0, [<<"1">>]},
+        meta = [{ref, make_ref()}]
```
Comment (iilyak) [inline src/couch/src/couch_db_updater.erl]: interesting approach

**Comment by eiri** [comment]
@iilyak I've extracted `increment_local_doc_revs` into a separate function as you suggested. Can you take a look, please, if this is what you had in mind?

**Comment by iilyak** [comment]
Perfect. Thank you @eiri.
