### PR TITLE
Port delayed_commits test to Elixir

### LINKED ISSUE #1704: Test suite `delayed_commits.js` unreliable.
It became quite often that JS tests fail on Travis with the following

```bash 
test/javascript/tests/delayed_commits.js                       
    Error: Failed to execute HTTP request: Failed to connect to 127.0.0.1 port 15984: Connection refused
Trace back (most recent call first):
    
  37: test/javascript/couch_http.js
      ("\"false\"\n")
 468: 127.0.0.1/_config/couchdb/delayed_commits",[object Object])@test/javascript/couch.js
      ("PUT","/_node/node1
 408: test/javascript/couch_test_runner.js
      run_on_modified_server([object Array],(function () {sleep(15000);T(db.
  29: test/javascript/tests/delayed_commits.js
      ()
  37: test/javascript/cli_runner.js
      runTest()
  48: test/javascript/cli_runner.js
      
fail
```

## Expected Behavior
JS tests should pass.

## Current Behavior
JS tests fail often locally in `delayed_commits` suite.

## Possible Solution
It's either some changes introduced with new purge functionality or some tweaking happened around JS suite itself. A bit of digging what exactly `delayed_commits` is testing and how that part of functionality was affected in the latest changes is required.

## Steps to Reproduce (for bugs)
Run `make javascript` until the failure. Note that isolated run `make javascript suites=delayed_commits` most of the time finishes fine.

### PR DESCRIPTION
**Pull request by eiri**
## Overview

This PR adds a new helper function to `test_helper` allowing to restart a node or the whole cluster and ports `delayed_commits` test.

## Testing recommendations

`make elixir` should pass, output log should include:
```
...
DelayedCommitsTest
  * test delayed commit (9208.3ms)
...
```

## Related Issues or Pull Requests

Closes #1704 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

File: test/elixir/test/delayed_commits_test.exs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+  Note that delayed_commits is deprecated in 2.0, so this is a minimal
+  test to show it still works. delayed_commits will be removed in 3.0.
+  """
+
+  @tag config: [
+         {"couchdb", "delayed_commits", "true"}
+       ]
+  @tag :with_db
+  test "delayed commit", context do
```
Comment (iilyak) [inline test/elixir/test/delayed_commits_test.exs]: The implementation of delayed commits is prune to race conditions since it is implemented using send_after see https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db_updater.erl#L742. The timeout is only one second. Which makes the test a flaky one. I would recommend wrapping all steps with `retry_until(fn -> ... true end)`

File: test/elixir/test/delayed_commits_test.exs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    db_name = context[:db_name]
+    doc_id = "doc-1"
+    resp = Couch.put("/#{db_name}/#{doc_id}", body: %{a: 2, b: 4})
+    assert resp.status_code >= 201
```
Comment (iilyak) [inline test/elixir/test/delayed_commits_test.exs]: This would also return true for error codes. You can use `resp.status_code in (201..204)` or something like that.

File: test/elixir/test/delayed_commits_test.exs [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    assert resp.body["ok"]
+
+    resp = Couch.get("/#{db_name}/#{doc_id}")
+    assert resp.status_code == 200, "The new doc should be in the database"
```
Comment (iilyak) [inline test/elixir/test/delayed_commits_test.exs]: thank you for using explanation argument for assertion.

File: test/elixir/test/delayed_commits_test.exs (hunk 1 above)
Comment (iilyak) [reply test/elixir/test/delayed_commits_test.exs]: There is a slight problem with using `retry_until`. Most likely it would swallow the exception when timeout is reached so we wouldn't see nice error message. Maybe we need to talk to @jaydoane to extend it to re-raise original error.

File: test/elixir/test/test_helper.exs [hunk 4]
```diff
@@ -259,6 +259,59 @@ defmodule CouchTestCase do
...
+            port = node_to_port(node)
+            [{node, port} | acc]
+          end)
+
+        tasks =
+          Enum.map(nodes_ports, fn {node, port} ->
+            Task.async(fn -> restart_node(node, port) end)
+          end)
+
+        Task.yield_many(tasks, length(nodes) * 5000)
```
Comment (iilyak) [inline test/elixir/test/test_helper.exs]: Good idea to make timeout depend on number of nodes.

File: test/elixir/test/delayed_commits_test.exs (hunk 1 above)
Comment (eiri) [reply test/elixir/test/delayed_commits_test.exs]: This test is racy pretty much by definition, though most of the problems with its javascript version coming not from the fact that it takes more than one second to _send_ a node to a restart, but that the cluster doesn't come back in time.

I'm honestly sceptical about usage of `retry_until` here. It has default timeout at 5 secs and this test takes whooping 9 sec on my MBP with the whole cluster bounce. I can wrap it with something like 10 sec retry interval and total timeout 30 secs, but this is pretty big band aid, so I'd prefer to actually see that race where doc saved before cluster bounce before extending the suites' runtime that much.

File: test/elixir/test/delayed_commits_test.exs (hunk 2 above)
Comment (eiri) [reply test/elixir/test/delayed_commits_test.exs]: Good idea. Fixed.

File: test/elixir/test/test_helper.exs [hunk 5]
```diff
@@ -259,6 +259,59 @@ defmodule CouchTestCase do
...
+        port = node_to_port(node)
+        restart_node(node, port)
+      end
+
+      defp restart_node(node, port) do
+        url = "http://127.0.0.1:#{port}/_node/#{node}/_restart"
+        resp = Couch.post(url)
+        assert HTTPotion.Response.success?(resp)
+        assert resp.body["ok"]
+        # make sure node went down. we assuming the node can't bounce quick
```
Comment (iilyak) [inline test/elixir/test/test_helper.exs]: If we want to be extra cautious we could use `uptime` to detect node restart.
```
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
218
$ http --auth=adm:pass POST :15984/_node/node2@127.0.0.1/_restart
HTTP/1.1 200 OK
Cache-Control: must-revalidate
Content-Length: 12
Content-Type: application/json
Date: Fri, 07 Dec 2018 14:59:18 GMT
Server: CouchDB/2.3.0-fcd62ed-dirty (Erlang OTP/19)
X-Couch-Request-ID: b5b6d5b302
X-CouchDB-Body-Time: 0

{
    "ok": true
}

$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
null
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
null
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
null
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
null
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
0
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
1
$ http --auth=adm:pass :15984/_node/node2@127.0.0.1/_system | jq .uptime
2
```

File: test/elixir/test/test_helper.exs [hunk 6]
```diff
@@ -259,6 +259,59 @@ defmodule CouchTestCase do
...
+        # wait utill node is back
+        retry_until(fn -> node_is_running(port) end, 500, 10000)
+      end
+
+      defp node_is_running(port) do
+        url = "http://127.0.0.1:#{port}/_up"
+        resp = Couch.get(url)
+
+        case HTTPotion.Response.success?(resp) do
+          true -> resp.status_code >= 200 && resp.status_code < 400
```
Comment (iilyak) [inline test/elixir/test/test_helper.exs]: `resp.status_code in (200 .. 399)`

File: test/elixir/test/test_helper.exs (hunk 5 above)
Comment (eiri) [reply test/elixir/test/test_helper.exs]: I think this is an overkill. Checking that node went down, then got back should be enough to make sure we have our restart.

File: test/elixir/test/test_helper.exs (hunk 6 above)
Comment (eiri) [reply test/elixir/test/test_helper.exs]: Hm.. This does the same thing, you know. I don't see ranges used for status code assertion anywhere else in existing elixir tests, so are you just expressing your personal preferences?

Comment (eiri) [reply test/elixir/test/test_helper.exs]: Well, whatever, I think my variant is more readable, but I don't care. Changed

**Comment by eiri** [comment]
@iilyak sorry, it's not clear to me - are you blocking this PR over `retry_until` and `uptime` or just got distracted by something else?

File: test/elixir/test/delayed_commits_test.exs (hunk 3 above)
Comment (van-mronov) [reply test/elixir/test/delayed_commits_test.exs]: Could it be useful to define a bunch of helper functons(`json_response/2`, `text_response/2`) like [Phoenix](https://github.com/phoenixframework/phoenix/blob/4da40a29f968b6e834ab55849af4a7337815ea50/lib/phoenix/test/conn_test.ex#L417) did?
But pass `%HTTPotion.Response{}` instead of `Plug.Conn`.
So we can do something like:

```elixir
resp = Couch.get("/#{db_name}/#{doc_id}")
assert %{"ok" => true} = json_response(resp, 200)
```
or
```elixir
resp = Couch.get("/#{db_name}/#{doc_id}")
assert %{"error" => _error} = json_response(resp, 404)
```

Comment (eiri) [reply test/elixir/test/delayed_commits_test.exs]: In my opinion that would do more harm than good. I believe that writing tests is inherently different from writing "normal" code and in former the simplicity and readability should be always prioritized over tersity.

When I write
```
assert resp.status_code == 200
assert resp.body == ${"ok" => true}
```
I can scan these lines and instantly understand what's going on here.

If i hide it into wrapper
```
assert %{"ok" => true} = json_response(resp, 200)
```
sure I saved one line, but now I have to stop and parse what exactly happening here. Unless I remember exactly what `json_response/2` does I have to guess: is that `200` a status code? Is the function going to raise an exception if status code not `200` or return `false`? Is any body transformation happening "under the hood"?

In general I'd prefer us to introduce code obfuscating changes to tests only when it's absolutely unavoidable.

Comment (eiri) [reply test/elixir/test/delayed_commits_test.exs]: 1) I don't find the second example more readable. 2) A thing that'd require a new or occasional test writer to stop and look into documentation or helper's code is an unnecessary hurdle. 3) I don't see a point to discuss here our personal opinion on the test writing. I suggest you to open a separate GH issue on this topic for a broader audience.
