### PR TITLE
Fix bug in replicator authentication for password contains @

### LINKED ISSUE #2892: Replicator authentication breaks if password contains @
## Description
It looks like CouchDB 3.0 does not correctly handle replication urls with credentials containing an `@` char. Other preserved characters does not seem to cause any problems, though.

The correct way for basic auth urls is to percent encode (e.g. using encodeURIComponent()) the credential part, see [chapter 2 of the URI RFC](http://www.faqs.org/rfcs/rfc3986.html). For example, consider a username `bob@me.com` and a password `secure`, a basic auth url would look like this: `https://bob%40me.com:secure@example.com`.

There are different ways to trigger replications, but I have only tested the issue with the classic `_replicate` endpoint. Here we post a JSON specifying the replication, eg:

```json
{
  "source": "https://couch.example.com/my-db",
  "target": "https://anothercouch.example.com/another-db"
}
```

If the databases are protected, we can use basic authentication:

```json
{
  "source": "https://alice:password@couch.example.com/my-db",
  "target": "https://bob:password@anothercouch.example.com/another-db"
}
```

And this is where we were hit. Now our password contained an @ char, for example p@ssword. The correct way to supply the password would be:

```json
{
  "source": "https://alice:password@couch.example.com/my-db",
  "target": "https://bob:p%40ssword@anothercouch.example.com/another-db"
}
```

We can circumvent this problem by using the object syntax for replication source and target:

```json
{
  "source": {
    "url": "https://couch.example.com/my-db",
    "headers": {
      "Authorization": "Basic YWxpY2U6cGFzc3dvcmQ="
    }
  },
  "target": {
    "url":  "https://anothercouch.example.com/another-db",
    "headers": {
      "Authorization": "Basic Ym9iOnBAc3N3b3Jk"
    }
}
```

The Authorization headers include the base64 encoded credential string like the usual Basic auth header:

```sh
echo -n "alice:password" | base64
echo -n "bob:p@ssword" | base64
```

### Start a couch. I used Docker for this:
```sh
docker run --rm -p 5984:5984 --name couchdb -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin couchdb:3.0
```
and set `COUCHDB_ADMIN_URL` environment variable including admin credentials for convenience:

```sh
export COUCHDB_ADMIN_URL="http://admin:admin@localhost:5984"
```

### Configure an admin user containing `@` char:
```sh
curl -XPUT "$COUCHDB_ADMIN_URL/_node/nonode@nohost/_config/admins/bob" -d '"p@ssword"'
```
### Create a db to replicate

```sh
curl -XPUT "$COUCHDB_ADMIN_URL/alice-db"
```

### Issue replication
```sh
curl -XPOST "$COUCHDB_ADMIN_URL/_replicate"  \
  -H 'Content-Type:application/json' \
  -d "{\"source\": \"$COUCHDB_ADMIN_URL/alice-db\", \"target\": \"http://bob:p%40ssword@localhost:5984/alice-db-copy-for-bob\", \"create_target\": true }"
```
replication fails with 

```
{"error":"replication_auth_error","reason":"{session_request_unauthorized,\"http://localhost:5984/_session\",\"bob\"}"}
```

## Expected Behaviour
* URLs provided in replication requests should support basic authentication even if special chars like `@` is used, in which case the credentials part should be percent encoded.

## Your Environment
* CouchDB version used: 3.0.0

### PR DESCRIPTION
**Pull request by jiahuili430**
## Overview
When the username and password contains @, the replicator authentication will break.
This PR fixes that bug by unquoting the credentials.

## Testing recommendations
make eunit apps=couch_replicator suites=couch_replicator_auth_session

## Related Issues or Pull Requests
This fixes #2892

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

**Comment by bessbd** [comment]
The build looks broken - the CI fail looks unrelated to the change. I'll open a PR to fix.

**Review by nickva — APPROVED** [review]
Nice work, @jiahuili430!

It's worth pointing out that if users properly quote their usernames and passwords they would still get an error when using just the basic auth (`noop`) plugin. In that case `ibrowse_lib:parse_url/1` would parse the quoted user:pass combination from the url, but then it won't unquote it before inserting into the basic auth header. However that is a separate issue to fix later.

(For full disclosure since we collaborated on the issue, I'd like another contributor to review the PR as well)

**Comment by iilyak** [comment]
My concern is uri encoding of a user name. The `couch_peruser` uses user name as part of a database name. Which means that it might be possible to inject things into filename (3.x puts dbname in a filename). I don't have proof or exploit at the moment.

**Comment by nickva** [comment]
@iilyak wouldn't the users be able to encode the username in basic auth headers anyway even outside the replicator code?

File: src/couch_replicator/src/couch_replicator_auth_session.erl [hunk 1]
```diff
@@ -288,7 +288,9 @@ extract_creds_from_url(Url) ->
             Prefix = lists:concat([Proto, "://", User, ":", Pass, "@"]),
             Suffix = lists:sublist(Url, length(Prefix) + 1, length(Url) + 1),
             NoCreds = lists:concat([Proto, "://", Suffix]),
-            {ok, User, Pass, NoCreds}
+            User1 = mochiweb_util:unquote(User),
+            Pass1 = mochiweb_util:unquote(Pass),
```
Comment (iilyak) [inline src/couch_replicator/src/couch_replicator_auth_session.erl:292]: I think we should call [`chttpd:unquote/1`](https://github.com/apache/couchdb/blob/main/src/chttpd/src/chttpd.erl#L678) here instead. This would make moving away from mochiweb framework easier in the future.

**Comment by iilyak** [comment]
> @iilyak wouldn't the users be able to encode the username in basic auth headers anyway even outside the replicator code?

True however we never attempt to unquote the user. This means that it would stay encoded. Encoded value is ok to use as filename. When we are trying to unquote it we are opening can of worms.

**Comment by nickva** [comment]
@iilyak

We don't unquote usernames during authz because they are in a base64-encoded blob in the  `"Authorization" : "Basic ..."` headers so there is no reason to quote them. When they are specified as the userinfo part of the URL some characters cannot be represented in that section of the URL, so they users would percent-encode (quote) them.

**Comment by iilyak** [comment]
I am pretty sure it is exploitable. I didn't try the whole PR. However in remsh you can do this.

1. I created a file in my home directory `echo "hello" > ~/bar`
2. My couchdb instance is located in the following dir `~/dev/couchdb`
3. I entered erlang shell `ERL_LIBS=(pwd)/src erl`
4. Then I issued the following (see https://github.com/apache/couchdb/blob/3.x/src/couch/src/couch_file.erl#L469 and https://github.com/apache/couchdb/blob/3.x/src/couch/src/couch_file.erl#L413)
```
f(Fd), {ok, Fd} = file:open(mochiweb_util:unquote("..%2F..%2Fbar"), [read, raw, binary,append]).
file:write(Fd, <<"garbage">>).
```
5. Finally I verified the content of a `~/bar` file
```
✦ ❯ cat ~/bar
hello
garbage⏎
```

The atacker can corrupt any file on the filesystem.

**Comment by iilyak** [comment]
It looks like we are encoding the username before constructing the database name for peruserdb use case https://github.com/apache/couchdb/blob/3.x/src/couch_peruser/src/couch_peruser.erl#L318

**Comment by nickva** [comment]
> I am pretty sure it is exploitable. 

I guess I still don't see how it's related to this replicator PR. All this logic happens the replicator (client) side, any client could or would specify basic auth credential in the exact same way?

**Comment by iilyak** [comment]
> > I am pretty sure it is exploitable.
> 
> I guess I still don't see how it's related to this replicator PR. All this logic happens on the replicator (client) side, any client could or would specify basic auth credential in the exact same way?

I forgot it is about client side.

**Review by iilyak — APPROVED** [review]
+1

File: src/couch_replicator/src/couch_replicator_auth_session.erl (hunk 1 above)
Comment (iilyak) [reply src/couch_replicator/src/couch_replicator_auth_session.erl:292]: There are pros and cons to either way. For example `chttpd` is not mentioned as a dependency in the app file. However we do call functions from `chttpd`. I am fine with leaving it as is.

**Comment by iilyak** [comment]
Great work @jiahuili430 !!!

**Comment by nickva** [comment]
@iilyak ah no worries, thanks for taking a look!

File: src/couch_replicator/src/couch_replicator_auth_session.erl (hunk 1 above)
Comment (jiahuili430) [reply src/couch_replicator/src/couch_replicator_auth_session.erl]: Thanks for reviewing my PR @iilyak, I replaced the quoted line... and waiting for the tests to pass now.
