### PR TITLE
Don't crash on invalid inline attachments

### LINKED ISSUE #784: Passing "stub": false without passing the attachment causes an unknown_error
If you're uploading a document with attachments and you say it's not a stub without then also passing the attachment, you get an unfriendly error and an exception thrown in the log.

## Expected Behavior
There should be a clean and readable error similar to when `"stub": true` and the attachment missing.

## Current Behavior
You get `{"error":"unknown_error","reason":"function_clause","ref":93628465}` returned and the log shows:
```
[error] 2017-08-31T14:17:53.315121Z couchdb@localhost <0.23961.0> 6cdd28e8a6 req_err(93628465) unknown_error : function_clause
    [<<"base64:decode/1 L114">>,<<"couch_att:inline_from_json/2 L411">>,<<"couch_doc:-transfer_fields/2-lc$^0/1-2-/1 L235">>,<<"couch_doc:transfer_fields/2 L235">>,<<"couch_doc:from_json_obj_validate/1 L129">>,<<"chttpd_db:db_req/2 L328">>,<<"chttpd:process_request/1 L295">>,<<"chttpd:handle_request_int/1 L231">>]
[notice] 2017-08-31T14:17:53.315363Z couchdb@localhost <0.23961.0> 6cdd28e8a6 localhost:5984 127.0.0.1 undefined POST /attachment-test 500 ok 1
```

## Steps to Reproduce (for bugs)
To follow along:
```
scdf at SCdF in ~
$ curl -X PUT http://admin:pass@localhost:5984/attachment-test
{"ok":true}
scdf at SCdF in ~
$ curl -X POST -H 'Content-Type: application/json' http://admin:pass@localhost:5984/attachment-test -d '{    "_id": "attachment-test",    "_attachments": {        "static/manifest.json": {            "content
_type": "application/json",            "digest": "md5-aFoQ0Neouur23mVxaLYoNA==",            "length": 30
3,            "revpos": 88,            "stub": true        }    }}'
{"error":"missing_stub","reason":"Invalid attachment stub in attachment-test for static/manifest.json"}
scdf at SCdF in ~
$ curl -X POST -H 'Content-Type: application/json' http://admin:pass@localhost:5984/attachment-test -d '{    "_id": "attachment-test",    "_attachments": {        "static/manifest.json": {            "content_type": "application/json",            "digest": "md5-aFoQ0Neouur23mVxaLYoNA==",            "length": 303,            "revpos": 88,            "stub": false        }    }}'
{"error":"unknown_error","reason":"function_clause","ref":93628465}
```
Note:
 - In the first `POST` I pass `"stub": true` and I get a nice error about not passing the attachment
 - In the second `POST` I changed stub from `true` to `false`, and we get the unfriendly `"unknown_error"` error message.

## Your Environment

* Version used: CouchDB 2.1.0
* Operating System and version (desktop or mobile): MacOS 10.12.6

### PR DESCRIPTION
**Pull request by eiri**
## Overview

We trust inline attachment to be base64 encoded, so in case it's not provided or invalidly encoded the upload request crashes with `function_clause`.

The change catches decode attempt and re-throws it as 400 error.

## Testing recommendations

Standard eunit and javascript tests should pass.

## GitHub issue number

Fixes #784 

## Checklist

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [ ] Documentation reflects the changes;

### CODE REVIEW

File: src/couch/src/couch_att.erl [hunk 1]
```diff
@@ -786,8 +794,35 @@ attachment_disk_term_test_() ->
...
+        {data, stub},
+        {encoding, identity}
+    ]),
+    ResultFollows = ResultStub#att{data = follows},
+    ResultInline = ResultStub#att{md5 = <<>>, data = <<"{\"answer\": 42}">>},
+    {"JSON term tests", [
+        ?_assertEqual(ResultStub, stub_from_json(Att, Props)),
+        ?_assertEqual(ResultFollows, follow_from_json(Att, Props)),
+        ?_assertEqual(ResultInline, inline_from_json(Att, PropsInline)),
+        ?_assertThrow({bad_request, _}, inline_from_json(Att, Props))
```
Comment (nickva) [inline src/couch/src/couch_att.erl]: In this case the data would be undefined so the case when data is not available at all in the request. Maybe have another clause where data is present but is invalid?

Comment (eiri) [reply src/couch/src/couch_att.erl]: This covers the original's issue exception, but sure, I'll add another test.

File: src/couch/src/couch_att.erl [hunk 2]
```diff
@@ -412,13 +412,21 @@ follow_from_json(Att, Props) ->
...
+    try base64:decode(B64Data) of
+        Data ->
+            Length = size(Data),
+            RevPos = couch_util:get_value(<<"revpos">>, Props, 0),
+            store([
+                {data, Data}, {revpos, RevPos}, {disk_len, Length},
+                {att_len, Length}
+            ], Att)
+    catch
+        _:_ ->
```
Comment (nickva) [inline src/couch/src/couch_att.erl]: Wonder if we should be more conservative and explicitly match on the knows exception tags and error message

```
error:function_clause
 
error:{badmatch, _}
```
the `function_clause` happens when is an invalid input data type such as undefined or list.

`badmatch` happens if type is correct but data is not a valid B64 encoding.

But I guess it's not clear that there couldn't be other errors thrown so maybe catching all is ok there. Docs don't say what exactly should be thrown.

So up to you here. I am 50/50 on this one.

Comment (eiri) [reply src/couch/src/couch_att.erl]: I thought about it, but then decided to opt out. We don't particularly interested in _how_ `base64` can't decode our data, only in fact that it can't be decoded, so there are no merit to try and match all possible ways `base64` can break, if at the end we are raising the same invalid request exception.

Comment (nickva) [reply src/couch/src/couch_att.erl]: Yap got it, that makes sense

**Comment by eiri** [comment]
@nickva Had to revert spec restoration commit, apparently R16 still doesn't know about `dict()` type

**Comment by nickva** [comment]
Ah ok, cool. Still approved, merge it when ready.
