### PR TITLE
Make changes feed return bad request for invalid heartbeat values

### LINKED ISSUE #2234: /db/_changes feed continuous mode does not return bad request for negative heartbeat values
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your actual CouchDB! )

Using a negative heartbeat value does not return a 400 bad request, instead getting just an empty response with no status code at all.

## Steps to Reproduce

[NOTE]: # ( Include commands to reproduce, if possible. curl is preferred. )

```
$ curl -XPUT http://localhost:5984/foodb
{"ok":true}
$ curl -v 'http://localhost:5984/foodb/_changes?feed=continuous&heartbeat=-1000'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 5984 (#0)
> GET /foodb/_changes?feed=continuous&heartbeat=-1000 HTTP/1.1
> Host: localhost:5984
> User-Agent: curl/7.54.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

According to https://docs.couchdb.org/en/2.3.1/api/database/changes.html#get--db-_changes `heartbeat` should be a `Period in milliseconds` or `true to use default value` thus any negative value should result in a `400 Bad Request` response.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
[TIP]:  # ( You can paste the output of curl http://YOUR-COUCHDB:5984/ here. )

```
$ curl http://localhost:5984/
{"couchdb":"Welcome","version":"2.3.1","git_sha":"c298091a4","uuid":"367155b102e015037fa9f1e1f18bf655","features":["pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

### PR DESCRIPTION
**Pull request by bessbd**
## Overview

Using a negative heartbeat value does not return a 400 bad request, instead getting just an empty response with no status code at all.

This commit adds extra checks so that negative and non-integer heartbeat values return 400 bad request responses.

## Testing recommendations

The changes has been tested manually:
```
[donat:~/couchdb] changes-feed-input-validation 1 ± curl -XPUT http://127.0.0.1:15984/asd
{"ok":true}
[donat:~/couchdb] changes-feed-input-validation ± curl -v http://127.0.0.1:15984/asd/_changes?feed=continuous\&heartbeat=-1000
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 15984 (#0)
> GET /asd/_changes?feed=continuous&heartbeat=-1000 HTTP/1.1
> Host: 127.0.0.1:15984
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Cache-Control: must-revalidate
< Content-Length: 60
< Content-Type: application/json
< Date: Wed, 23 Oct 2019 15:10:52 GMT
< Server: CouchDB/3.0.0-1dd00d6ac (Erlang OTP/22)
< X-Couch-Request-ID: 61d1b854bd
< X-CouchDB-Body-Time: 0
<
{"error":"bad_request","reason":"Negative heartbeat value"}
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
[donat:~/couchdb] changes-feed-input-validation ± curl -v http://127.0.0.1:15984/asd/_changes?feed=continuous\&heartbeat=a1000
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 15984 (#0)
> GET /asd/_changes?feed=continuous&heartbeat=a1000 HTTP/1.1
> Host: 127.0.0.1:15984
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Cache-Control: must-revalidate
< Content-Length: 59
< Content-Type: application/json
< Date: Wed, 23 Oct 2019 15:11:01 GMT
< Server: CouchDB/3.0.0-1dd00d6ac (Erlang OTP/22)
< X-Couch-Request-ID: 4e9ae14ede
< X-CouchDB-Body-Time: 0
<
{"error":"bad_request","reason":"Invalid heartbeat value"}
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0
```
Also, there are new test cases added for the new behavior.

## Related Issues or Pull Requests

This fixes #2234

## Checklist

- [X] Code is written and works correctly
- [X] Changes are covered by tests
- [X] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [X] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation

### CODE REVIEW

File: src/chttpd/src/chttpd_db.erl [hunk 1]
```diff
@@ -1816,7 +1816,14 @@ parse_changes_query(Req) ->
         {"heartbeat", "true"} ->
             Args#changes_args{heartbeat=true};
         {"heartbeat", _} ->
-            Args#changes_args{heartbeat=list_to_integer(Value)};
+            try list_to_integer(Value) of
+                V when V > 0 ->
+                    Args#changes_args{heartbeat=heartbeat_integer};
```
Comment (iilyak) [inline src/chttpd/src/chttpd_db.erl]: I don't think `heartbeat_integer` is correct.
```
Args#changes_args{heartbeat=heartbeat_integer};
```

**Comment by iilyak** [comment]
> @iilyak Would you mind writing a test case for it.

I am so sorry I missed the fact that you have some tests

File: src/chttpd/src/chttpd_db.erl (hunk 1 above)
Comment (bessbd) [reply src/chttpd/src/chttpd_db.erl]: Good call! I've just pushed a commit to fix this.

File: src/chttpd/src/chttpd_db.erl [hunk 2]
```diff
@@ -1816,7 +1816,14 @@ parse_changes_query(Req) ->
         {"heartbeat", "true"} ->
             Args#changes_args{heartbeat=true};
         {"heartbeat", _} ->
-            Args#changes_args{heartbeat=list_to_integer(Value)};
+            try list_to_integer(Value) of
+                HeartbeatInteger when HeartbeatInteger > 0 ->
+                    Args#changes_args{heartbeat=HeartbeatInteger};
+                _ ->
+                    throw({bad_request, <<"Negative heartbeat value">>})
```
Comment (iilyak) [inline src/chttpd/src/chttpd_db.erl]: The "Negative heartbeat value" doesn't sound correct if user pass `0`. Should we change the wording to something like:
- The heartbeat value should be positive integer

File: src/chttpd/src/chttpd_db.erl [hunk 3]
```diff
@@ -1816,7 +1816,14 @@ parse_changes_query(Req) ->
...
+            catch error:badarg ->
+                throw({bad_request, <<"Invalid heartbeat value">>})
```
Comment (iilyak) [inline src/chttpd/src/chttpd_db.erl]: It would be better to give user a hint. Something like:
```
<<"Invalid heartbeat value. Expecting positive integer value (in milliseconds).">>
```

**Comment by bessbd** [comment]
@iilyak : thank you for the review! I've just pushed a commit (cabe4c4) to make the changes you've suggested.

**Comment by iilyak** [comment]
@bessbd Could you squash commits.

**Comment by bessbd** [comment]
> @bessbd Could you squash commits.

Done!

**Comment by iilyak** [comment]
Thank you for your contribution.

**Comment by bessbd** [comment]
Thank you for the review and the merge, @iilyak !
