### PR TITLE
In _scheduler/docs fix `crashing` state showing as `pending` sometimes

### LINKED ISSUE #1276: Return "crashing" state from `_scheduler/docs` immediately after the first crash
When a replication job that has been running for a while crashes with an error and is stopped. It status in `_scheduler/docs` endpoint response should be `crashing` instead of `pending`.

The `crashing` vs `pending` status is driven by the "consecutive errors" count. This is computed as the number of crashes that occur in a row, for example a crash soon after a job start or a crash soon after another crash. If the crash happens a long enough time after a job start or previous crash then consecutive errors count is reset to 0 and the job is considered healthy.

So this sequence of steps is possible. A user starts a job, lets it run for 5 minutes then deletes the source. The output of `_scheduler/docs` will show state = `pending` since consecutive crashes is still 0, but the user would rather see state as `crashing` in the result.

The fix is so return crashing if a crash is the last even in the job history even if errors count is still 0.

### PR DESCRIPTION
**Pull request by nickva**
Replication jobs are backed off based on the number of consecutive crashes,
that is, we count the number of crashes in a row and then penalize jobs with an
exponential wait based that number. After a job runs without crashing for 2
minutes, we consider it healthy and stop going back in its history and looking
for crashes.

Previously a job's state was set to `crashing` only if there were any
consecutive errors. So it could have ran for 3 minutes, then user deletes the
source database, job crashes and stops. Until it runs again the state would
have been shown as `pending`. For internal accounting purposes that's correct
but it is confusing for the user because the last event in its history is a
crash.

This commit makes sure that if the last even in job's history is a crash user
will see the jobs as `crashing` with the respective crash reason. The
scheduling algorithm didn't change.

Fixes #1276

- [x] Code is written and works correctly;
- [x] Changes are covered by tests;
- [x] Documentation reflects the changes;

### CODE REVIEW

File: src/couch_replicator/src/couch_replicator_scheduler.erl [hunk 1]
```diff
@@ -138,11 +138,15 @@ job_summary(JobId, HealthThreshold) ->
             ErrorCount = consecutive_crashes(History, HealthThreshold),
             {State, Info} = case {Pid, ErrorCount} of
                 {undefined, 0}  ->
-                    {pending, null};
+                    case History of
```
Comment (tonysun83) [inline src/couch_replicator/src/couch_replicator_scheduler.erl]: Since we're checking History in both instances of ErrorCount could we do it like this:

```
{undefined, _ErrorCount} ->
    case History of
         [{{crashed, Error}, _When} | _] ->
             {crashing, crash_reason_json(Error)};
         [_ | _] ->
             {pending, null}
    end,
```
?

Comment (nickva) [reply src/couch_replicator/src/couch_replicator_scheduler.erl]: The difference is that when it is 0 we only show an error if the last event is an error, otherwise it is pending. So it is really a `pending` case mostly so I left it that way to make it clear to think about "pending, crashing and running".
