### PR TITLE
Couch password server process

### LINKED ISSUE #4236: Unstable configuration when adding multiple admins at the same time ​
​## Description
​
If you add multiple admin accounts in parallel the configuration of couchdb may get into an "unstable" state where passwords hashes change continuously or in some cases passwords won't be hashed at all. After some time couchdb may get back into a stable state, but the amount of time seems to increase exponentially with the number of accounts added in parallel.
​
## Environment
​
Tested on a single node instance and on a specific node of a cluster instance of couchdb using the latest official docker image (`3.2.2`).
​
## Steps to reproduce
​
On a single node instance you can add multiple accounts in parallel using the following command:
​
```bash
seq 1 20 | xargs -n1 -P20 -I {} curl -X PUT -u admin:admin http://localhost:5984/_node/_local/_config/admins/admin{} -d '"password{}"'
```
​
If you want to try this on a cluster you should replace `_local` with a specific node name.
​
CouchDB will start logging messages like the following very fast:
​
```
[notice] 2022-10-20T13:06:56.868984Z nonode@nohost <0.103.0> -------- config: [admins] admin16 set to '****' for reason nil
[notice] 2022-10-20T13:06:56.869598Z nonode@nohost <0.103.0> -------- config: [admins] admin16 set to '****' for reason nil
[notice] 2022-10-20T13:06:56.870323Z nonode@nohost <0.103.0> -------- config: [admins] admin16 set to '****' for reason nil
```
​
And if you check the admins using
​
```bash
curl -X GET -u admin:admin http://localhost:5984/_node/_local/_config/admins
```
​
or by displaying directly the configuration file
​
```bash
cat /opt/couchdb/etc/local.d/docker.ini
```
​
you will see that it will have some cleartext passwords and some hashes will change continuously between requests, for example:
​
```json
{
  // omitted
  "admin5": "-pbkdf2-d23d834fc32321310c1d64eb98d08b190a1afe89,02211c4e01b0898347f61785cbf444fc,10",
  // omitted
  "admin19": "password19",
  // omitted
}
```
​
```json
{
  // omitted
  "admin5": "-pbkdf2-8e4518204b831cabc335f661fdee03906c20f01c,8cef6ad463898bf3303407f3fbf3f5c0,10",
  // omitted
  "admin19": "password19",
  //omitted
}
```
​
After enough time some of the cleartext passwords may be hashed.

—

The problem is here: https://github.com/apache/couchdb/blob/main/src/couch/src/couch_server.erl#L382-L385 every time there is a config change, we spawn a process to do the password hashing. 

Those processes race in the above scenario.

IIRC we did this knowing it can be a problem and assuming clients would throttle.

Given erlang, making this a queue shouldn’t be so hard, maybe we can find a beginner-contributor volunteer? :)

### PR DESCRIPTION
**Pull request by big-r81**
First draft PR to create a `gen_server` process, which hashes the admin passwords from the configuration file.

~~It gets started in `couch_sup`.~~
Gets started in couch_primary_services now.

PR needs some more polish.

In the current state, this PR already fixes #4236.

### CODE REVIEW

File: src/couch/src/couch_password_server.erl [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+start_link() ->
+    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
+
+init(_Args) ->
+    {ok, #state{}}.
+
+handle_call(hash_passwords, _From, _State) ->
+    {reply, hash_admin_passwords(), _State};
+handle_call(_Request, _From, State = #state{}) ->
+    {reply, ok, State}.
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:55]: Let's stop and crash with an invalid_call message here. This service shouldn't be getting unexpected calls.

File: src/couch/src/couch_password_server.erl [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+
+handle_cast(hash_passwords, _State) ->
+    hash_admin_passwords(),
+    {noreply, _State};
+handle_cast(_Request, State) ->
+    {noreply, State}.
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:61]: Let's stop and crash as well

File: src/couch/src/couch_password_server.erl [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+
+handle_info(_Info, State = #state{}) ->
+    {noreply, State}.
+
+terminate(_Reason, _State = #state{}) ->
+    ok.
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:67]: I think these two callbacks might be optional these days. See if you remove them and everything still work as expected.

File: src/couch/src/couch_password_server.erl (hunk 1 above)
Comment (big-r81) [reply src/couch/src/couch_password_server.erl:55]: So we would have a `{stop, invalid_call, State}`?

Comment (nickva) [reply src/couch/src/couch_password_server.erl:55]: Maybe `{stop, {invalid_call, Msg}, {invalid_call, Msg}, State}.` just so the caller also gets a reply about it

File: src/couch/src/couch_sup.erl [hunk 4]
```diff
@@ -168,3 +169,8 @@ write_file(FileName, Contents) ->
             couch_log:error("Failed ot write ~s :: ~s", Args),
             throw({error, Reason})
     end.
+
+start_password_server() ->
+    couch_log:info("Password Server Process is starting.~n", []),
+    couch_password_server:start_link(),
+    ok.
```
Comment (nickva) [inline src/couch/src/couch_sup.erl:176]: If we intend this to be properly supervised we should add it to the supervisor as a child. `couch_primary_services` might be a better place for it, right before the couch_server instances are added.

File: src/couch/src/couch_password_server.erl [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+handle_call({hash_passwords, Persist}, _From, _State) ->
+    {reply, hash_admin_passwords(Persist), _State};
+handle_call(Msg, _From, State = #state{}) ->
+    {stop, {invalid_call, Request}, {invalid_call, Request}, State}.
+
+handle_cast({hash_passwords, Persist}, _State) ->
+    hash_admin_passwords(Persist),
+    {noreply, _State};
+handle_cast(Msg, State) ->
+    {stop, {invalid_call, Msg}, State}.
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:63]: `invalid_cast` ?

File: src/couch/src/couch_sup.erl (hunk 4 above)
Comment (big-r81) [reply src/couch/src/couch_sup.erl:176]: So, put it into Children of `couch_primary_services`, or where to add?

File: src/couch/src/couch_password_server.erl [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+%%%===================================================================
+
+start_link() ->
+    couch_log:info("Password Hasher Process is starting.~n", []),
+    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
+
+init(_Args) ->
+    {ok, #state{}}.
+
+handle_call({hash_passwords, Persist}, _From, _State) ->
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:55]: If `_State` is used it should be `State`. Let's match it like below as well just in case `#state{} =State`

File: src/couch/src/couch_password_server.erl [hunk 7]
```diff
@@ -0,0 +1,80 @@
...
+    {reply, hash_admin_passwords(Persist), _State};
+handle_call(Msg, _From, State = #state{}) ->
+    {stop, {invalid_call, Msg}, {invalid_call, Msg}, State}.
+
+handle_cast({hash_passwords, Persist}, _State) ->
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:60]: `_State` is used, it should not have an underscore. As above, let's use `#state{} = State`

File: src/couch/src/couch_password_server.erl [hunk 8]
```diff
@@ -0,0 +1,80 @@
...
+start_link() ->
+    couch_log:info("Password Hasher Process is starting.~n", []),
+    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
+
+init(_Args) ->
+    {ok, #state{}}.
+
+handle_call({hash_passwords, Persist}, _From, _State) ->
+    {reply, hash_admin_passwords(Persist), _State};
+handle_call(Msg, _From, State = #state{}) ->
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:57]: `#state{} = State` is a bit more common I think?

File: src/couch/src/couch_password_server.erl [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+    {stop, {invalid_call, Msg}, {invalid_call, Msg}, State}.
+
+handle_cast({hash_passwords, Persist}, _State) ->
+    hash_admin_passwords(Persist),
+    {noreply, _State};
+handle_cast(Msg, State) ->
+    {stop, {invalid_cast, Msg}, State}.
+
+code_change(_OldVsn, State = #state{}, _Extra) ->
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:66]: as above, `#state{} = State` is a bit more common

File: src/couch/src/couch_server.erl [hunk 10]
```diff
@@ -381,7 +369,7 @@ handle_config_change("couchdb_engines", _, _, _, N) ->
     {ok, N};
 handle_config_change("admins", _, _, Persist, N) ->
     % spawn here so couch event manager doesn't deadlock
-    spawn(fun() -> hash_admin_passwords(Persist) end),
+    couch_password_server:hash(true, Persist),
```
Comment (nickva) [inline src/couch/src/couch_server.erl:372]: I wonder if another problem here is that we'll be rehashing the password N times, once for each couch_server? For instance on a 96 cpu server, we'll rehash the password 96 times in parallel, it seems.

An ideal way to handle it might be to just remove the password rehashing from here to the new password hasher gen_server, which we have one of. So it would have the `handle_config_change` callback and so on. A quicker hack for now could be to only handle admin rehashing for `N=1`. Also do the same for httpd changes, we don't need to stop/restart the httpd backend N times.

File: src/couch/src/couch_password_server.erl (hunk 6 above)
Comment (big-r81) [reply src/couch/src/couch_password_server.erl:55]: > If `_State` is used it should be `State`. 
Yes, that makes sense.

> Let's match it like below as well just in case `#state{} = State`
Btw, I personally find this spelling unnatural, maybe i'm too much "left-to-right" indoctrinated ;-). But it seems common practice and I will change.

File: src/couch/src/couch_password_server.erl (hunk 8 above)
Comment (big-r81) [reply src/couch/src/couch_password_server.erl:57]: Same as above, will change.

File: src/couch/src/couch_password_server.erl (hunk 5 above)
Comment (big-r81) [reply src/couch/src/couch_password_server.erl]: Ah yes, good find

File: src/couch/src/couch_password_server.erl (hunk 6 above)
Comment (nickva) [reply src/couch/src/couch_password_server.erl:55]: The idea is that we're not making a var equal to State, but asserting that it matches an existing value, the reverse order sort of highlights that.

File: src/couch/src/couch_server.erl (hunk 10 above)
Comment (big-r81) [reply src/couch/src/couch_server.erl:372]: Is N the number of Nodes in the cluster or the Number of processors?

Comment (big-r81) [reply src/couch/src/couch_server.erl:372]: Or can we use the `State` record to call to number of unhashed passwords and only start the hashing if it's greater than zero?

Comment (nickva) [reply src/couch/src/couch_server.erl:372]: `N` is the couch_server process number `1 ... $(number_of_schedulers)`. So in handle_config_change ... we'd replace `N` with `1`. So the first couch_server would do the hashing or stopping of httpd and the rest would ignore it.

File: src/couch/src/couch_password_server.erl [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+        false ->
+            gen_server:call(?MODULE, {hash_passwords, Persist})
+    end.
+
+%%%===================================================================
+%%% Spawning and gen_server implementation
+%%%===================================================================
+
+start_link() ->
+    couch_log:info("Password Hasher Process is starting.~n", []),
```
Comment (nickva) [inline src/couch/src/couch_password_server.erl:49]: Let's skip the log line. If it doesn't start we'll get an error in the logs and otherwise we'll assume it started.

File: src/couch/src/couch_server.erl (hunk 10 above)
Comment (nickva) [reply src/couch/src/couch_server.erl:372]: To debug this try to log N and the rest of the state and then in remsh do something like `config:set("admins", "adm5", "pass5").`

File: src/couch/src/couch_password_server.erl (hunk 11 above)
Comment (big-r81) [reply src/couch/src/couch_password_server.erl:49]: Ok.

File: src/couch/src/couch_server.erl (hunk 10 above)
Comment (big-r81) [reply src/couch/src/couch_server.erl:372]: So, I pattern-matched the call for the server with Number 1, do we need to handle the "admin" for other servers too?

Comment (nickva) [reply src/couch/src/couch_server.erl:372]: For others it can just be a fall-through and nothing will happen:

This case basically:

```erlang
handle_config_change(_, _, _, _, N) ->
    {ok, N}.
```

Comment (big-r81) [reply src/couch/src/couch_server.erl:372]: Ok.

**Review by nickva — APPROVED** [review]
+1 nicely done!

Used recon to check N=1 check works properly. 
```
(node1@127.0.0.1)1> recon_trace:calls({couch_password_server, '_', '_'}, 100).
8
(node1@127.0.0.1)2> config:set("admins", "adm3", "pass3").
ok

13:1:17.467839 <0.137.0> couch_password_server:hash(true, true)

13:1:17.473463 <0.287.0> couch_password_server:handle_cast({hash_passwords,true}, {state})

13:1:17.473770 <0.137.0> couch_password_server:hash(true, true)

13:1:17.474088 <0.287.0> couch_password_server:handle_cast({hash_passwords,true}, {state})
(node1@127.0.0.1)3> config:set("admins", "adm4", "pass4", false).

13:1:37.865566 <0.137.0> couch_password_server:hash(true, false)

13:1:37.865983 <0.287.0> couch_password_server:handle_cast({hash_passwords,false}, {state})
ok

13:1:37.866447 <0.137.0> couch_password_server:hash(true, false)

13:1:37.866809 <0.287.0> couch_password_server:handle_cast({hash_passwords,false}, {state})
```

Don't forget to squash your commits. I noticed two separate commits with the exact same commit message :-)

File: src/couch/src/couch_password_hasher.erl [hunk 12]
```diff
@@ -0,0 +1,75 @@
...
+%%%===================================================================
+
+start_link() ->
+    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).
+
+init(_Args) ->
+    hash_admin_passwords(true),
+    {ok, #state{}}.
+
+handle_call({hash_passwords, Persist}, _From, State) ->
```
[the remark this answers is not in the document]
Comment (big-r81) [reply src/couch/src/couch_password_hasher.erl]: yeah, good idea!
