### PR TITLE
Fix query limit

### LINKED ISSUE #5176: Query exporting only 2ˆ28 documents (data have more) even after setting query limit to 2ˆ29
# Description

We're working with a CouchDB database that holds about 272 million records. When attempting to retrieve all documents using a curl command and writing to a file, we noticed that only 268435456 records were returned, despite the database having more entries.

The curl command in question:

`curl -k -X GET "https://$(cat credential_couchdb)@{host}/{db}/_all_docs?include_docs=true" > all_docs`

This led us to suspect a default query limit issue, which aligns with discussions in [this GitHub pull request](https://github.com/apache/couchdb/pull/1804).

To resolve this, we updated the config file to set both partition_query_limit and query_limit to 536870912 (2^29).

`"query_server_config":{"partition_query_limit":"536870912","query_limit":"536870912"}`

Despite this change and the _offset_ field from the output file displaying the correct amount of total records, the output still holds 268435456 records.

# Expected Behaviour
We expect the number of records in the output file to match the _offset_ field value, not to be stuck in this default value count.

# Additional Context
The CouchDB instance in question is integrated as a state database within a Hyperledger Fabric setup.
The database is updated once a day.

@lucasmation

### PR DESCRIPTION
**Pull request by nickva**
Previously, we set a default limit that was an effective infinity (2^28). It seems back in the 32 bit days that was the Erlang's largest small integer [1]. However, that turned out to be too low and it surprised a user when it truncated their all_docs output skipping some of the data. Fix that by increasing the limit to a larger "infinity" (highest 64 bit Erlang small integer [1]).

We did have a "query_limit" config parameter to customize the limit, however that turned out to be broken and did not take effect when the user tried it for all_docs, so fix that as well. Test to ensure the limit gets reduced appropriately. To make the setting more user friendly, allow `infinity` as the value.

Also, in the case of all_docs, we validated args and applied the limit check twice: once in the coordinator and another time on each worker, which wasted CPU resources and made things a bit confusing. To fix that, remove the validation from the common worker code in couch_mrview and validate once: either on the coordinator side, or local (port 5986) callback, right in the http callback.

[1] https://www.erlang.org/doc/system/memory.html

Fix #5176

### CODE REVIEW

File: src/couch_mrview/src/couch_mrview.erl [hunk 1]
```diff
@@ -279,20 +279,20 @@ query_all_docs(Db, Args) ->
     query_all_docs(Db, Args, fun default_cb/2, []).
 
 query_all_docs(Db, Args, Callback, Acc) when is_list(Args) ->
-    query_all_docs(Db, to_mrargs(Args), Callback, Acc);
+    Args1 = couch_mrview_util:validate_all_docs_args(Db, to_mrargs(Args)),
```
Comment (nickva) [inline src/couch_mrview/src/couch_mrview.erl:282]: This clause is not called from a clustered endpoint, only from a test.

File: src/couch_mrview/src/couch_mrview.erl [hunk 2]
```diff
@@ -279,20 +279,20 @@ query_all_docs(Db, Args) ->
...
+    query_all_docs(Db, Args1, Callback, Acc);
 query_all_docs(Db, Args0, Callback, Acc) ->
     Sig = couch_util:with_db(Db, fun(WDb) ->
         {ok, Info} = couch_db:get_db_info(WDb),
         couch_index_util:hexsig(couch_hash:md5_hash(?term_to_bin(Info)))
     end),
     Args1 = Args0#mrargs{view_type = map},
-    Args2 = couch_mrview_util:validate_all_docs_args(Db, Args1),
```
Comment (nickva) [inline src/couch_mrview/src/couch_mrview.erl:289]: Remove validation here and validate once in fabric or in couch*http modules instead

File: src/couch_mrview/include/couch_mrview.hrl [hunk 3]
```diff
@@ -54,7 +54,8 @@
     view_states=nil
 }).
 
--define(MAX_VIEW_LIMIT, 16#10000000).
+% Largest 64 bit small int: 2^59-1
+-define(MAX_VIEW_LIMIT, 16#7FFFFFFFFFFFFFF).
```
Comment (nickva) [inline src/couch_mrview/include/couch_mrview.hrl:58]: Use `infinity` in .ini files to make it more user-friendly.

File: src/chttpd/src/chttpd_db.erl [hunk 4]
```diff
@@ -948,14 +948,12 @@ multi_all_docs_view(Req, Db, OP, Queries) ->
 
 all_docs_view(Req, Db, Keys, OP) ->
     Args0 = couch_mrview_http:parse_body_and_query(Req, Keys),
-    Args1 = Args0#mrargs{view_type = map},
-    Args2 = fabric_util:validate_all_docs_args(Db, Args1),
```
Comment (nickva) [inline src/chttpd/src/chttpd_db.erl:952]: Validation now happens in `fabric:all_docs()`

File: src/couch_mrview/src/couch_mrview_util.erl [hunk 5]
```diff
@@ -522,11 +522,11 @@ apply_limit(ViewPartitioned, Args) ->
             {false, _} -> "query_limit"
         end,
 
-    MaxLimit = config:get_integer(
-        "query_server_config",
-        LimitType,
-        ?MAX_VIEW_LIMIT
-    ),
+    MaxLimit =
+        case config:get("query_server_config", LimitType, "infinity") of
```
Comment (jaydoane) [inline src/couch_mrview/src/couch_mrview_util.erl:526]: Nice ergonomic improvement!

File: src/couch_mrview/src/couch_mrview_http.erl [hunk 6]
```diff
@@ -241,7 +241,8 @@ do_all_docs_req(Req, Db, Keys, NS) ->
         ),
         IsAdmin = is_admin(Db),
         Callback = get_view_callback(DbName, UsersDbName, IsAdmin),
-        couch_mrview:query_all_docs(Db, Args, Callback, VAcc0)
+        ValidatedArgs = couch_mrview_util:validate_all_docs_args(Db, Args),
```
Comment (jaydoane) [inline src/couch_mrview/src/couch_mrview_http.erl:244]: I ran `make eunit` and looked at coverage, but unfortunately this module looks pretty uncovered
```
couch_mrview_http  6%
```
And in particular this line does not get unit tested.

File: src/couch_mrview/src/couch_mrview_show.erl [hunk 7]
```diff
@@ -224,7 +224,8 @@ handle_view_list(Req, Db, DDoc, LName, VDDoc, VName, Keys) ->
             Acc = #lacc{db = Db, req = Req, qserver = QServer, lname = LName},
             case VName of
                 <<"_all_docs">> ->
-                    couch_mrview:query_all_docs(Db, Args, fun list_cb/2, Acc);
+                    ValidatedArgs = couch_mrview_util:validate_all_docs_args(Db, Args),
```
Comment (jaydoane) [inline src/couch_mrview/src/couch_mrview_show.erl:227]: This line is also not covered by unit tests.

File: src/fabric/src/fabric_util.erl [hunk 8]
```diff
@@ -326,6 +326,8 @@ is_partitioned(DbName0) when is_binary(DbName0) ->
 is_partitioned(Db) ->
     couch_db:is_partitioned(Db).
 
+validate_all_docs_args(DbName, Args) when is_list(DbName) ->
+    validate_all_docs_args(list_to_binary(DbName), Args);
```
Comment (jaydoane) [inline src/fabric/src/fabric_util.erl:330]: Also not covered by unit tests.

**Review by jaydoane — APPROVED** [review]
Nice improvement, but I'm a little worried that you've moved validation around without explicitly testing that validation. Is it worth adding a couple more tests to tighten that up?

**Comment by nickva** [comment]
Good idea, Jay, to add a few more tests. I assumed we tested those somewhere else already but it's apparently not the case.

File: src/couch_mrview/src/couch_mrview_http.erl (hunk 6 above)
Comment (nickva) [reply src/couch_mrview/src/couch_mrview_http.erl:244]: Thanks! I added a set of http "local" query tests in a addition to just calling `query_all_docs` directly.

File: src/couch_mrview/src/couch_mrview_show.erl (hunk 7 above)
Comment (nickva) [reply src/couch_mrview/src/couch_mrview_show.erl:227]: Thank you. It turns out we didn't have any local _list tests, just chttpd ones. So I added a new test suite for local _list functions.

File: src/fabric/src/fabric_util.erl (hunk 8 above)
Comment (nickva) [reply src/fabric/src/fabric_util.erl:330]: Add a quick test for fabric all docs. The `DbName` as a list is more of a remsh script kind of a affordance. But since we supported it before, I thought it's good to keep the compatibility.
