### PR TITLE
Validate target doc id for COPY method

### LINKED ISSUE #5117: doc COPY requests allow bypass of ID validity check
Docs can be created with illegal IDs by using the [`COPY` method](https://docs.couchdb.org/en/stable/api/document/common.html#copy--db-docid).

## Steps to Reproduce

```
curl -vvv http://admin:password@localhost:5984/main/some-doc \
     -X COPY \
     -H 'Destination: _bad_path'
```

## Expected Behaviour

Illegal doc IDs should be rejected.

## Your Environment

* CouchDB version used: 3.3

### PR DESCRIPTION
**Pull request by rnewson**
closes #5117

## Overview

The COPY handler did not validate the target doc id, allowing the insertion of doc ids that begin with `_`, which is prohibited by all other document creation methods.

## Testing recommendations

unit tests

## Related Issues or Pull Requests

https://github.com/apache/couchdb/issues/5117

## Checklist

- [x] Code is written and works correctly
- [x] Changes are covered by tests
- [ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [ ] Documentation changes were made in the `src/docs` folder
- [ ] Documentation changes were backported (separated PR) to affected branches

### CODE REVIEW

**Review by janl — APPROVED** [review]

File: src/couch/src/couch_httpd_db.erl [hunk 1]
```diff
@@ -685,6 +685,7 @@ db_doc_req(#httpd{method = 'COPY'} = Req, Db, SourceDocId) ->
         end,
     {TargetDocId0, TargetRevs} = parse_copy_destination_header(Req),
     TargetDocId = list_to_binary(mochiweb_util:unquote(TargetDocId0)),
+    couch_db:validate_docid(Db, TargetDocId),
```
Comment (alxndrsn) [inline src/couch/src/couch_httpd_db.erl:688]: what's the difference between this and the similar code above (`chttpd_db.erl`)?

Comment (rnewson) [reply src/couch/src/couch_httpd_db.erl:688]: that's for the legacy 5986 node-local interface, just here for completeness.
